export const ACR_TITLE = {
    title: "Marketplace Acronyms Search",
    subtitle: "Predictive Search. Start typing the abbreviation you are looking for",
    about: "This is a search of the acronyms used in PI Planning presentation materials. Start typing abbreviation you are looking for"
}

export const ACR_ARR = [
    {id: 1, name: "A/B", val: "Agents and Brokers"},
    {id: 2, name: "ACC", val: "Akamai Control Center"},
    {id: 3, name: "ACK", val: "Acknowledgment"},
    {id: 4, name: "ACT", val: "Adaptive Controls Testing"},
    {id: 5, name: "ADJ", val: "Adjudication"},
    {id: 6, name: "ADO", val: "Application Development Organization"},
    {id: 7, name: "AEM", val: "Adobe Experience Manager"},
    {id: 8, name: "AL2", val: "Amazon Linux2"},
    {id: 9, name: "AMI", val: "Amazon Machine Image"},
    {id: 10, name: "API", val: "Application Programming Interface"},
    {id: 11, name: "App 2", val: "Marketplace 2.0 Application"},
    {id: 12, name: "App 3.0", val: "Marketplace 3.0 Application"},
    {id: 13, name: "APTC", val: "Advance Premium Tax Credit"},
    {id: 14, name: "A/R", val: "Authorized Representative"},
    {id: 15, name: "AR", val: "Advanced Resolution"},
    {id: 16, name: "ARP", val: "American Rescue Plan Act"},
    {id: 17, name: "ART", val: "Agile Release Train"},
    {id: 18, name: "AT", val: "Account Transfer"},
    {id: 19, name: "ATO", val: "Authority to Operate"},
    {id: 20, name: "AW", val: "Appeals Worker"},
    {id: 21, name: "AWS", val: "Amazon Web Service"},
    {id: 22, name: "BAR", val: "Batch Auto Re-enrollment"},
    {id: 23, name: "BEDAP", val: "Beneficiary Experience Data Analytics Portal"},
    {id: 24, name: "BI", val: "Business Impact"},
    {id: 25, name: "BPC", val: "Business Planning and Consolidation"},
    {id: 26, name: "BPC", val: "Business Process Correspondence"},
    {id: 27, name: "BUU", val: "Batch Update Utility"},
    {id: 28, name: "BYOS", val: "Bring Your Own Subscription"},
    {id: 29, name: "CBCI", val: "CloudBees Continuous Improvement"},
    {id: 30, name: "CCIC", val: "CMS Cybersecurity Integration Center (CCIC)"},
    {id: 31, name: "CCIIO", val: "Center for Consumer Information and Insurance Oversight"},
    {id: 32, name: "CCM", val: "Cloud Content Manager"},
    {id: 33, name: "CCR", val: "Call Center Representative"},
    {id: 34, name: "CCXP", val: "Care Choice Experience"},
    {id: 35, name: "CFACTS", val: "CMS FISMA Controls Tracking System"},
    {id: 36, name: "CHIP", val: "Children's Health Insurance Program"},
    {id: 37, name: "CI", val: "Continuous Improvement"},
    {id: 38, name: "CIC", val: "Change in Circumstance"},
    {id: 39, name: "CLI ", val: "Command Line Interface"},
    {id: 40, name: "CMS", val: "Centers for Medicare & Medicaid Services"},
    {id: 41, name: "COFA", val: "Compacts of Free Association"},
    {id: 42, name: "CORR", val: "Correspondence"},
    {id: 43, name: "COTS", val: "Commercial Off-the-Shelf"},
    {id: 44, name: "CR", val: "Continuing Resolution?"},
    {id: 45, name: "CSI", val: "Current Sources of Income"},
    {id: 46, name: "CSR", val: "Customer Service Representative"},
    {id: 47, name: "CU", val: "Change Utility Eligibility Support Desktop Change Utility"},
    {id: 48, name: "ESDCU", val: "Change Utility Eligibility Support Desktop Change Utility"},
    {id: 49, name: "CVP", val: "Customer Value Partners"},
    {id: 50, name: "DE", val: "Direct Enrollment"},
    {id: 51, name: "DEG", val: "Determine Enrollment Group"},
    {id: 52, name: "DMI", val: "Data Matching Issue"},
    {id: 53, name: "DS", val: "DocuSign"},
    {id: 54, name: "DSH", val: "Data Services Hub"},
    {id: 55, name: "DSIS", val: "Division of State IT Support"},
    {id: 56, name: "DSRS", val: "Document Storage and Retrieval Service"},
    {id: 57, name: "DVE", val: "Determine Variable Eligibility"},
    {id: 58, name: "DWO", val: "Division of Website Operations"},
    {id: 59, name: "EACMS", val: "Eligibility Appeals Case Management System"},
    {id: 60, name: "EBS", val: "Elastic Block Storage"},
    {id: 61, name: "EC2", val: "AWS Elastic Compute Cloud"},
    {id: 62, name: "E-CAP", val: "Encription Correction Action Plan"},
    {id: 63, name: "ECM", val: "EDGE Calculation Module"},
    {id: 64, name: "ECWS", val: "Exchange Consumer Web Services"},
    {id: 65, name: "EDE", val: "Enhanced Direct Enrollment"},
    {id: 66, name: "EDGE", val: "External Data Gathering Environment"},
    {id: 67, name: "EDH", val: "Enrollment Data History"},
    {id: 68, name: "EDI", val: "Electronic Data Interchange"},
    {id: 69, name: "EDN", val: "Eligibility Determination Notice"},
    {id: 70, name: "EE", val: "Eligibility and Enrollment"},
    {id: 71, name: "E&E", val: "Eligibility and Enrollment"},
    {id: 72, name: "EFT", val: "Electronic File Transfer"},
    {id: 73, name: "EPM", val: "Enrollment Processing Module"},
    {id: 74, name: "ER&R", val: "Enrollment Reconciliation and Resolution"},
    {id: 75, name: "ESD", val: "Enterprise Systems Development"},
    {id: 76, name: "ESCMEC", val: "Employer Sponsored Coverage Minimum Essential Coverage"},
    {id: 77, name: "ESW", val: "Eligibility Support Workers"},
    {id: 78, name: "EUA", val: "Enterprise User Administration"},
    {id: 79, name: "EVAAS", val: "Eligibility Verification-as-a-Service"},
    {id: 80, name: "EWST", val: "Enterprise Web Support Tool"},
    {id: 81, name: "F5 BIGIP", val: "Load Balancers"},
    {id: 82, name: "F5 Big-IP", val: "Load Balancers"},
    {id: 83, name: "FA", val: "Financial Assistance"},
    {id: 84, name: "FA/nonFA", val: "Financial Assistance / Non-Financial Assistance"},
    {id: 85, name: "FedRAMP", val: "Federal Risk and Authorization Management Program"},
    {id: 86, name: "FFE", val: "Federally Facilitated Exchange"},
    {id: 87, name: "FFM", val: "Federally Facilitated Marketplace"},
    {id: 88, name: "FHO", val: "Federal Hearing Officer"},
    {id: 89, name: "FISMA", val: "Federal Information Security Management Act"},
    {id: 90, name: "FLH", val: "Find Local Help"},
    {id: 91, name: "FM", val: "Financial Management"},
    {id: 92, name: "FPUC", val: "Federal Payment Unemployment Compensation"},
    {id: 93, name: "FTR", val: "Failureto File and Reconcile"},
    {id: 94, name: "G4", val: "Platform Google Analytics 4"},
    {id: 95, name: "GA4", val: "Google Analytics 4"},
    {id: 96, name: "GA4", val: "Google Analytics"},
    {id: 97, name: "GTM", val: "Global Traffic Management"},
    {id: 98, name: "HCV", val: "Health Coverage Verification"},
    {id: 99, name: "HHS", val: "Health & Human Services"},
    {id: 100, name: "HIOS", val: "Health Insurance Oversight System"},
    {id: 101, name: "HPF", val: "Health Plan Finder"},
    {id: 102, name: "HRA", val: "Health Reimbursement Arrangement"},
    {id: 103, name: "Hub", val: "Data Services Hub"},
    {id: 104, name: "HUBESDCU", val: "Change Utility"},
    {id: 105, name: "ESDCU", val: "Eligibility Support Desktop Change Utility"},
    {id: 106, name: "IDE", val: "Integrated Development Environment"},
    {id: 107, name: "IDM", val: "Identity Management, typically in the context of the IDM system owned by OIT"},
    {id: 108, name: "IES", val: "Insurance Enrollment Services"},
    {id: 109, name: "IEM", val: "Infrastructure Event Management"},
    {id: 110, name: "IMPL1B", val: "testing/production environment"},
    {id: 111, name: "IP", val: "Iteration Planning"},
    {id: 112, name: "IRS", val: "Internal Revenue Service"},
    {id: 113, name: "ISAVE", val: "Independent Systems Acceptance and Verification for the Exchange"},
    {id: 114, name: "ISERV", val: "Internet Services"},
    {id: 115, name: "ISSO", val: "Information Systems Security Officer"},
    {id: 116, name: "ITPM", val: "Information Technology Program Manager"},
    {id: 117, name: "ITSI", val: "IT Service Intelligence"},
    {id: 118, name: "IVT/ECAT", val: "Income Verification Tool/Employer Coverage Affordability Tool"},
    {id: 119, name: "JDK", val: "Java Development Kit"},
    {id: 120, name: "JMaas", val: "JMeter as a Service"},
    {id: 121, name: "JMeter", val: "load testing tool in services and web applications"},
    {id: 122, name: "JSON", val: "JavaScript Object Notation"},
    {id: 123, name: "KPI", val: "name Performance Indicator"},
    {id: 124, name: "LA", val: "Language Assistance"},
    {id: 125, name: "LE", val: "Large Employer"},
    {id: 126, name: "LEARN", val: "JavaScript Object Notation"},
    {id: 127, name: "LLE", val: "Lower Level Environment"},
    {id: 128, name: "LTO", val: "Long Term Objective"},
    {id: 129, name: "MAPI", val: "Marketplace Application Programming Interface"},
    {id: 130, name: "MaPS", val: "Marketplace Project Startup"},
    {id: 131, name: "MAX", val: "Medicare Authenticated Experience"},
    {id: 132, name: "MCR", val: "Marketplace Consumer Record"},
    {id: 133, name: "MCT", val: "Medicare Coverage Tools"},
    {id: 134, name: "MEF", val: "Mission Essential Function"},
    {id: 135, name: "MIDAS", val: "Multi-Dimensional Insurance Data Analytics System"},
    {id: 136, name: "MITG", val: "Marketplace Information Technology Group"},
    {id: 137, name: "ML", val: "MarkLogic"},
    {id: 138, name: "MLMS", val: "Marketplace Learning Management System"},
    {id: 139, name: "MNPS", val: "Marketplace Notice Production Services or Notices"},
    {id: 140, name: "MOCC", val: "Marketplace Operations Coordination Center"},
    {id: 141, name: "MODS", val: "Marketplace Outreach Data System"},
    {id: 142, name: "MOSS", val: "Microsoft Office SharePoint Server"},
    {id: 143, name: "MSI", val: "Marketplace Systems Integrator"},
    {id: 144, name: "MTS", val: "Marketplace Technical Review Board Semiannual Session"},
    {id: 145, name: "NAIC", val: "National Association of Insurance Commissioners"},
    {
        id: 146, name: "NIST",
        val: "National Institute of Standards and Technology - Security and Privacy Controls for Information Systems and Organizations"
    },
    {id: 147, name: "NR", val: "Non-renewal"},
    {id: 148, name: "NSA", val: "National Security Agency"},
    {id: 149, name: "OC", val: "Office of Communications"},
    {id: 150, name: "OC", val: "BIA Office of Communication Business Impact Analysis"},
    {id: 151, name: "OCF", val: "Office of Communication Foundational Team"},
    {id: 152, name: "OE", val: "Open Enrollment"},
    {id: 153, name: "OE8", val: "Open Enrollment 2021"},
    {id: 154, name: "OE9", val: "Open Enrollment 2022"},
    {id: 155, name: "OE10", val: "Open Enrollment 2023 (i.e. the 10th OE for the Marketplace"},
    {id: 156, name: "OEX", val: "Open Enrollment 2023 (i.e. the 10th OE for the Marketplace"},
    {id: 157, name: "OIT", val: "Office of Information Technology"},
    {id: 158, name: "OIV/MOEN", val: "Offline Income Verification/ Marketplace Open Enrollment Notices"},
    {id: 159, name: "OMB", val: "Office of Management & Budget"},
    {id: 160, name: "OPERA", val: "Operational Analytics"},
    {id: 161, name: "Ops&OE", val: "Operations & Open Enrollment"},
    {id: 162, name: "PC Classic", val: "Plan Compare Classic"},
    {id: 163, name: "PC2/WS", val: "Plan Compare 2.0/ WINSHOP or Window Shop"},
    {id: 164, name: "PCL", val: "Plan Category Limits"},
    {id: 165, name: "PDM", val: "Periodic Data Match"},
    {id: 166, name: "PET", val: "Premium Estimation Tool"},
    {id: 167, name: "PHI", val: "Protected Health Information"},
    {id: 168, name: "PI", val: "Program Increment"},
    {id: 169, name: "PII", val: "Personal Identifiable Information"},
    {id: 170, name: "PIA", val: "Privacy Impact Analysis"},
    {id: 171, name: "PIV", val: "Personal Identity Verification"},
    {id: 172, name: "PM", val: "Program Manager"},
    {id: 173, name: "PM ML", val: "Plan Management MarkLogic"},
    {id: 174, name: "POA&Ms", val: "Plan of Action and Milestones"},
    {id: 175, name: "PPL", val: "Procedure Price Loopup"},
    {id: 176, name: "PPM", val: "Payment Processing Module"},
    {id: 177, name: "PSC", val: "Program Support Center"},
    {id: 178, name: "PTC", val: "Premium Tax Credit"},
    {id: 179, name: "PTCSEP", val: "Premium Tax Credit Special Enrollment Period"},
    {id: 180, name: "PWSS", val: "Public Website Shared Services (FISMA system owned and maintained by OC.The system includes OC Shared Services as CloudBees CI, JFrog Artifactory, Kong EE, GEO API, LaunchDarkly,Mapbox, SmartyStreets, TestRail and other shared services)"},
    {id: 181, name: "QA", val: "Quality Assurance"},
    {id: 182, name: "QHP", val: "Qualified Health Plan"},
    {id: 183, name: "RDS", val: "Relational Database Service"},
    {id: 184, name: "REST", val: "Representational State Transfer"},
    {id: 185, name: "RFI", val: "Request for Information"},
    {id: 186, name: "RHEL", val: "Red Hat Enterprise Linux"},
    {id: 187, name: "RHELBYOS", val: "Red Hat Enterprise Linux - Bring Your Own Subscription"},
    {id: 188, name: "RI", val: "Requested Information"},
    {id: 189, name: "RIDP", val: "Remote Identify Proofing"},
    {id: 190, name: "ROAM", val: "Resolve Own Accept Mitigate"},
    {id: 191, name: "ROAMing", val: "Resolve Own Accept Mitigate"},
    {id: 192, name: "RTE", val: "Release Train Engineer"},
    {id: 193, name: "S3", val: "Amazon Simple Storage Service"},
    {id: 194, name: "SaaS", val: "Software-as-a-Service"},
    {id: 195, name: "SAFe", val: "Scaled Agile Framework"},
    {id: 196, name: "SAML", val: "Security Assertion Markup Language"},
    {id: 197, name: "SBE ", val: "State Based Exchange"},
    {id: 198, name: "SBEs", val: "State Based Exchange"},
    {id: 199, name: "SCOUT", val: "Security Control Orchestration Utilities and Tooling"},
    {id: 200, name: "SEED", val: "System of Exchange Enrollment Data"},
    {id: 201, name: "SEP", val: "Special Enrollment Period"},
    {id: 202, name: "SERFF", val: "System for Electronic Rate and Form Filing"},
    {id: 203, name: "SERS/SERVIS", val: "State Exchange Resource Virtual Information System"},
    {id: 204, name: "SES", val: "Standalone Eligibility Service"},
    {id: 205, name: "SIA", val: "Security Impact Analysis"},
    {id: 206, name: "SIT", val: "System Inventory Taker"},
    {id: 207, name: "SLS", val: "Scalable Login Service"},
    {id: 208, name: "SLSx", val: "Scalable Login Service"},
    {id: 209, name: "SMART(E)", val:"Specific Measurable Achievable Realistic Time-bound Excited"},
    {id: 210, name: "SMS", val: "Short Message Service"},
    {id: 211, name: "SNI", val: "Server Name Identification"},
    {id: 212, name: "SoS", val: "Scrum of Scrums"},
    {id: 213, name: "SSN", val: "Social Security Number"},
    {id: 214, name: "SSO", val: "Systems Security Officer"},
    {id: 215, name: "STP", val: "Short Term Priority"},
    {id: 216, name: "SVI", val: "SEP Verification Issue"},
    {id: 217, name: "TMS", val: "Transactional Messaging Service"},
    {id: 218, name: "TRB", val: "Technical Review Board"},
    {id: 219, name: "UI", val: "User Interface"},
    {id: 220, name: "URR", val: "Unified Rate Review"},
    {id: 221, name: "UX", val: "User Experience"},
    {id: 222, name: "VIP", val: "Virtual IP"},
    {id: 223, name: "VPC", val: "Virtual Private Clouds"},
    {id: 224, name: "WAF", val: "Web Application Firewall"},
    {id: 225, name: "WB", val: "Work Basket"},
    {id: 226, name: "WDS2", val: "Web Development Services 2 (Current Ad Hoc Contract)"},
    {id: 227, name: "WETGDWO", val: "Web and Emerging Technologies Group, Division of Website Ops"},
    {id: 228, name: "WL", val: "Work List"},
    {id: 229, name: "XOC", val: "Exchange Operations Center"},
    {id: 230, name: "ZONE", val: "CMS Opportunity to Network and Engage"},
]

